# Generated by Django 4.2.30 on 2026-06-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='active_exam_stage',
            field=models.CharField(choices=[('PT-01', 'Periodic Test 1 (PT-01)'), ('SA-01', 'Summative Assessment 1 (SA-01)'), ('PT-02', 'Periodic Test 2 (PT-02)'), ('SA-02', 'Summative Assessment 2 (SA-02)')], default='PT-01', max_length=10),
        ),
    ]
