# Generated by Django 4.2.30 on 2026-07-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_userloginstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('holiday', 'Holiday / Sunday Off'), ('event', 'School Event / Function'), ('working_sunday', 'Working Sunday (Override)')], default='holiday', max_length=20)),
            ],
        ),
    ]
